In [1]:
1+1

2

In [1]:
1+1

2

In [2]:
import numpy as np

In [5]:
## 1-d array
lst=[1,2,3]
arr=np.array(lst)

In [7]:
type(arr)

numpy.ndarray

In [11]:
arr1= np.array([[1,2,3],[4,5,6]])

In [12]:
## 2-d array
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.shape     ###  2 rows 3 columns

(2, 3)

In [14]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr1.reshape(1,6)     ### starting with two brackets and end also

array([[1, 2, 3, 4, 5, 6]])

In [16]:
arr1.dtype

dtype('int32')

In [20]:
### create your own array

np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
np.arange(1,8,2).reshape(4,1).shape   ## here 2 is step size

(4, 1)

In [26]:
np.arange(100,50,-3)  ### array of reverse order

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52])

In [31]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [43]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [48]:
np.ones((4,2,8))   ### 3-d array

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [3]:
5+np.ones((4,5))     ## broadcasting

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [4]:
np.identity(5).reshape((1,25))

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [8]:
np.random.rand(4,7)    ## uniform distribution

array([[0.39838722, 0.9331441 , 0.60453255, 0.99301524, 0.9269285 ,
        0.38791794, 0.06507887],
       [0.68516294, 0.82487514, 0.2182299 , 0.90964928, 0.48019765,
        0.37679664, 0.62223527],
       [0.82098148, 0.81081472, 0.63942437, 0.35430485, 0.29873496,
        0.13953988, 0.76825569],
       [0.05661319, 0.98727109, 0.50238457, 0.28250853, 0.65112932,
        0.04650238, 0.70767871]])

In [9]:
np.random.randn(3,5)     ### normal distribution

array([[ 0.67672845, -1.45470616,  0.00474387, -0.1849749 , -1.58436976],
       [ 0.91423065,  0.2576306 ,  0.27442136, -0.56813156,  1.46829088],
       [ 0.91821277,  0.12014865,  0.99675661, -0.67834599, -0.47836357]])

In [19]:

np.random.randint(1,100,(5,7))

array([[57,  2, 54, 31, 59, 71, 91],
       [34, 38, 10, 82, 65, 65,  6],
       [ 6, 84, 78, 36, 69, 30,  4],
       [94, 25, 95, 13,  2, 47, 36],
       [53, 57, 83, 58, 90, 68, 41]])

In [22]:
### slicing

arr3=np.arange(1,15)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
arr3[4:13]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [26]:
arr3[1:10:2]

array([ 2,  4,  6,  8, 10])

In [27]:
arr3[-4:4:-2]

array([11,  9,  7])

In [33]:
arr4=np.random.randint(2,100,20).reshape(5,4)
arr4

array([[96, 36, 17, 78],
       [84, 12, 69, 45],
       [85, 79, 93, 10],
       [81, 98, 10, 72],
       [98, 52, 87, 41]])

In [72]:
arr4[2:4,0:5:2]      #### assignment

array([[85, 93],
       [81, 10]])

In [77]:
### universal function

arr5=np.random.randint(1,50,(4,4))
arr6=np.random.randint(20,100,(4,4))

In [78]:
arr5

array([[20,  1, 25, 38],
       [ 4, 22,  6,  6],
       [ 2,  4, 20, 17],
       [32, 19,  8, 23]])

In [79]:
arr6

array([[98, 87, 71, 70],
       [41, 66, 68, 44],
       [21, 57, 75, 50],
       [89, 68, 94, 56]])

In [80]:
arr5 +arr6

array([[118,  88,  96, 108],
       [ 45,  88,  74,  50],
       [ 23,  61,  95,  67],
       [121,  87, 102,  79]])

In [81]:
arr5* arr6

array([[1960,   87, 1775, 2660],
       [ 164, 1452,  408,  264],
       [  42,  228, 1500,  850],
       [2848, 1292,  752, 1288]])

In [82]:
arr5/arr6

array([[0.20408163, 0.01149425, 0.35211268, 0.54285714],
       [0.09756098, 0.33333333, 0.08823529, 0.13636364],
       [0.0952381 , 0.07017544, 0.26666667, 0.34      ],
       [0.35955056, 0.27941176, 0.08510638, 0.41071429]])

In [83]:
arr5-arr6

array([[-78, -86, -46, -32],
       [-37, -44, -62, -38],
       [-19, -53, -55, -33],
       [-57, -49, -86, -33]])

In [84]:
np.sqrt(arr6)

array([[9.89949494, 9.32737905, 8.42614977, 8.36660027],
       [6.40312424, 8.1240384 , 8.24621125, 6.63324958],
       [4.58257569, 7.54983444, 8.66025404, 7.07106781],
       [9.43398113, 8.24621125, 9.69535971, 7.48331477]])

In [85]:
np.exp(arr5)

array([[4.85165195e+08, 2.71828183e+00, 7.20048993e+10, 3.18559318e+16],
       [5.45981500e+01, 3.58491285e+09, 4.03428793e+02, 4.03428793e+02],
       [7.38905610e+00, 5.45981500e+01, 4.85165195e+08, 2.41549528e+07],
       [7.89629602e+13, 1.78482301e+08, 2.98095799e+03, 9.74480345e+09]])

In [86]:
np.log10(arr6)

array([[1.99122608, 1.93951925, 1.85125835, 1.84509804],
       [1.61278386, 1.81954394, 1.83250891, 1.64345268],
       [1.32221929, 1.75587486, 1.87506126, 1.69897   ],
       [1.94939001, 1.83250891, 1.97312785, 1.74818803]])

In [88]:
arr7=np.arange(1,10)   ### broadcasting

In [89]:
arr7[2:]=100

In [90]:
arr7

array([  1,   2, 100, 100, 100, 100, 100, 100, 100])